version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@lukemurraynz"
    assignees:
      - "@lukemurraynz"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "dotnet"
    groups:
      microsoft-packages:
        patterns:
          - "Microsoft.*"
          - "Azure.*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "Microsoft.Graph"
        update-types: ["version-update:semver-major"]

  # Monitor GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"